<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Student_Clearance_Management_System</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <!-- AdminForm -->
    <Compile Update="Forms\AdminForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\AdminForm.Designer.cs">
      <DependentUpon>AdminForm.cs</DependentUpon>
    </Compile>

    <!-- StudentRegistrationForm -->
    <Compile Update="Forms\StudentRegistrationForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\StudentRegistrationForm.Designer.cs">
      <DependentUpon>StudentRegistrationForm.cs</DependentUpon>
    </Compile>

    <!-- StudentLoginForm -->
    <Compile Update="Forms\StudentLoginForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\StudentLoginForm.Designer.cs">
      <DependentUpon>StudentLoginForm.cs</DependentUpon>
    </Compile>

    <!-- StudentDashboard -->
    <Compile Update="Forms\StudentDashboard.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\StudentDashboard.Designer.cs">
      <DependentUpon>StudentDashboard.cs</DependentUpon>
    </Compile>

    <!-- ReEnterPasswordForm -->
    <Compile Update="Forms\ReEnterPasswordForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\ReEnterPasswordForm.Designer.cs">
      <DependentUpon>ReEnterPasswordForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\MSI\OneDrive\Desktop\C#\Student Clearance Management System\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\MSI\OneDrive\Desktop\C#\Student Clearance Management System\.editorconfig" />
  </ItemGroup>

</Project>